#!/bin/bash

function commandExists
{
  type "$1" &> /dev/null;
}

function checkDeps
{
  local depRequired=("dialog" "sqlite3")
  local depMissing=()
  for ((i=0; i<${#depRequired[@]}; i++))
  do
    local dep="${depRequired[$i]}"
    commandExists "${dep}"
    if [ "$?" -ne 0 ]; then
      depMissing+=("${dep}")
    fi
  done
  
  if [ ${#depMissing[@]} -gt 0 ]; then
    echo "There are missing dependencies:"
    for ((i=0; i<${#depMissing[@]}; i++))
    do
      echo " * ${depMissing[$i]}"
    done
    exit 1
  fi
}

function askForDirectoryPath
{
  chosenDir=$(dialog --stdout --title "Please choose a directory for the storage" --dselect $HOME 10 20)
  if [ $? -ne 0 ]; then
    echo "Directory path was not supplied."
    exit 1
  fi
  echo $chosenDir
}

# checking required dependencies
checkDeps

# retrieving directory path from the user
rootDir=$(askForDirectoryPath)

echo $rootDir
